### PR TITLE
Update postinstall.js to get at least the npm install working on windows

### PR DESCRIPTION
**Pull request by gero3**

### CODE REVIEW

**Comment by tomshaw** [comment]
As of Memorial Day I'm getting this error.

npm ERR! sm@0.1.76 postinstall: `node ./scripts/postinstall.js`
npm ERR! `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
npm ERR!
npm ERR! Failed at the sm@0.1.76 postinstall script.

**Comment by jedilando** [comment]
(Windows XP)

After

> npm install -g sm

I get:

> npm http GET https://registry.npmjs.org/sm
> ...
> C:\Documents and Settings\LND\Application Data\npm\sm -> C:\Documents and Settings\LND\Application Data\npm\node_modules\sm\bin\sm
> 
> sm@0.1.76 postinstall C:\Documents and Settings\LND\Application Data\npm\node_modules\sm
> node ./scripts/postinstall.js
> 
> C:\Documents and Settings\LND\Application Data\npm\node_modules\sm\scripts\postinstall.js:10
> TERM.stderr.writenl("\0yellow(Running as UID: " + process.getuid() + "\0)");
>                                                           ^
> TypeError: Object #<process> has no method 'getuid'
>     at Object.<anonymous> (C:\Documents and Settings\LND\Application Data\npm\node_modules\sm\scripts\postinstall.js:10:59)
>     at Module._compile (module.js:449:26)
>     at Object.Module._extensions..js (module.js:467:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.runMain (module.js:487:10)
>     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
> npm ERR! sm@0.1.76 postinstall: `node ./scripts/postinstall.js`
> npm ERR! `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
> npm ERR!
> npm ERR! Failed at the sm@0.1.76 postinstall script.
> npm ERR! This is most likely a problem with the sm package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./scripts/postinstall.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls sm
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! System Windows_NT 5.1.2600
> npm ERR! command "D:\_PROGRAMS\nodejs\\node.exe" "D:\_PROGRAMS\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "sm"
> npm ERR! cwd F:\dev\nodejs\aurora\cloud9
> npm ERR! node -v v0.8.1
> npm ERR! npm -v 1.1.33
> npm ERR! code ELIFECYCLE
> npm ERR! message sm@0.1.76 postinstall: `node ./scripts/postinstall.js`
> npm ERR! message `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     F:\dev\nodejs\aurora\cloud9\npm-debug.log
> npm ERR! not ok code 0

**Comment by bwasty** [comment]
I'm getting the same error on Win 7

**Comment by FissionCat** [comment]
Just tried installing with npm on Windows XP, got the same error.

**Comment by im007boy** [comment]
I'm getting the same error on Win 7

**Comment by seaneagan** [comment]
me too

**Comment by Racheet** [comment]
and me

**Comment by ogrisel** [comment]
I had the same issue under OSX and fixed it with:

```
export PATH=$PATH:/usr/local/share/npm/bin
```

and then re-running:

```
npm install -g sm
```

**Pull request closed without merging**
